package me.helleo.cwp.configurations;

import static me.helleo.cwp.configurations.ConfigLoader.getConfig;

public enum ConfigurationsDouble {
    // ENCHANT LEVELS
    EmeraldArmorEnchantLevels_Unbreaking(getConfig().getDouble("EmeraldArmorEnchantLevels.Unbreaking")),
    EmeraldArmorEnchantLevels_Mending(getConfig().getDouble("EmeraldArmorEnchantLevels.Mending")),
    EmeraldGearEnchantLevels_Unbreaking(getConfig().getDouble("EmeraldArmorEnchantLevels.Unbreaking")),
    EmeraldGearEnchantLevels_Mending(getConfig().getDouble("EmeraldArmorEnchantLevels.Mending")),
    ChorusEnchantLevels_Unbreaking(getConfig().getDouble("ChorusEnchantLevels.Unbreaking")),
    ChorusEnchantLevels_Knockback(getConfig().getDouble("ChorusEnchantLevels.KnockBack")),
    SwordBowEnchantLevels_Smite(getConfig().getDouble("SwordBowEnchantLevels.Smite")),
    SwordBowEnchantLevels_Unbreaking(getConfig().getDouble("SwordBowEnchantLevels.Unbreaking")),
    SwordBowEnchantLevels_Mending(getConfig().getDouble("SwordBowEnchantLevels.Mending")),
    HeavySwordBowEnchantLevels_Smite(getConfig().getDouble("HeavySwordBowEnchantLevels.Smite")),
    HeavySwordBowEnchantLevels_Power(getConfig().getDouble("HeavySwordBowEnchantLevels.Power")),
    HeavySwordBowEnchantLevels_Unbreaking(getConfig().getDouble("HeavySwordBowEnchantLevels.Unbreaking")),
    HeavySwordBowEnchantLevels_Mending(getConfig().getDouble("HeavySwordBowEnchantLevels.Mending")),
    PlatedChainmailEnchantLevels_Unbreaking(getConfig().getDouble("PlatedChainmailEnchantLevels.Unbreaking")),
    ObsidianEnchantLevels_Unbreaking(getConfig().getDouble("ObsidianEnchantLevels.Unbreaking")),
    DiamondShieldEnchantLevels_Unbreaking(getConfig().getDouble("DiamondShieldEnchantLevels.Unbreaking")),
    NetheriteShieldEnchantLevels_Unbreaking(getConfig().getDouble("NetheriteShieldEnchantLevels.Unbreaking")),
    // ARMORS
    Armors_RedstoneCore_Armor(getConfig().getDouble("Armors_RedstoneCore.Armor")),
    Armors_EmeraldHelmet_Armor(getConfig().getDouble("Armors_EmeraldHelmet.Armor")),
    Armors_EmeraldHelmet_BonusHealth(getConfig().getDouble("Armors_EmeraldHelmet.BonusHealth")),
    Armors_EmeraldChestplate_Armor(getConfig().getDouble("Armors_EmeraldChestplate.Armor")),
    Armors_EmeraldChestplate_BonusHealth(getConfig().getDouble("Armors_EmeraldChestplate.BonusHealth")),
    Armors_EmeraldLeggings_Armor(getConfig().getDouble("Armors_EmeraldLeggings.Armor")),
    Armors_EmeraldLeggings_BonusHealth(getConfig().getDouble("Armors_EmeraldLeggings.BonusHealth")),
    Armors_EmeraldBoots_Armor(getConfig().getDouble("Armors_EmeraldBoots.Armor")),
    Armors_EmeraldBoots_BonusHealth(getConfig().getDouble("Armors_EmeraldBoots.BonusHealth")),
    Armors_PlateChainHelmet_Armor(getConfig().getDouble("Armors_PlateChainHelmet.Armor")),
    Armors_PlateChainChestplate_Armor(getConfig().getDouble("Armors_PlateChainChestplate.Armor")),
    Armors_PlateChainLeggings_Armor(getConfig().getDouble("Armors_PlateChainLeggings.Armor")),
    Armors_PlateChainBoots_Armor(getConfig().getDouble("Armors_PlateChainBoots.Armor")),
    Armors_PrismarineHelmet_Armor(getConfig().getDouble("Armors_PrismarineHelmet.Armor")),
    Armors_PrismarineHelmet_ArmorToughness(getConfig().getDouble("Armors_PrismarineHelmet.ArmorToughness")),
    Armors_PrismarineHelmet_KBResist(getConfig().getDouble("Armors_PrismarineHelmet.KBResist")),
    Armors_PrismarineHelmet_BonusHealth(getConfig().getDouble("Armors_PrismarineHelmet.BonusHealth")),
    Armors_PrismarineChestplate_Armor(getConfig().getDouble("Armors_PrismarineChestplate.Armor")),
    Armors_PrismarineChestplate_ArmorToughness(getConfig().getDouble("Armors_PrismarineChestplate.ArmorToughness")),
    Armors_PrismarineChestplate_KBResist(getConfig().getDouble("Armors_PrismarineChestplate.KBResist")),
    Armors_PrismarineChestplate_BonusHealth(getConfig().getDouble("Armors_PrismarineChestplate.BonusHealth")),
    Armors_PrismarineLeggings_Armor(getConfig().getDouble("Armors_PrismarineLeggings.Armor")),
    Armors_PrismarineLeggings_ArmorToughness(getConfig().getDouble("Armors_PrismarineLeggings.ArmorToughness")),
    Armors_PrismarineLeggings_KBResist(getConfig().getDouble("Armors_PrismarineLeggings.KBResist")),
    Armors_PrismarineLeggings_BonusHealth(getConfig().getDouble("Armors_PrismarineLeggings.BonusHealth")),
    Armors_PrismarineBoots_Armor(getConfig().getDouble("Armors_PrismarineBoots.Armor")),
    Armors_PrismarineBoots_ArmorToughness(getConfig().getDouble("Armors_PrismarineBoots.ArmorToughness")),
    Armors_PrismarineBoots_KBResist(getConfig().getDouble("Armors_PrismarineBoots.KBResist")),
    Armors_PrismarineBoots_BonusHealth(getConfig().getDouble("Armors_PrismarineBoots.BonusHealth")),
    Armors_WitherHelmet_KBResist(getConfig().getDouble("Armors_WitherHelmet.KBResist")),
    Armors_WitherHelmet_BonusHealth(getConfig().getDouble("Armors_WitherHelmet.BonusHealth")),
    Armors_WitherChestplate_KBResist(getConfig().getDouble("Armors_WitherChestplate.KBResist")),
    Armors_WitherChestplate_BonusHealth(getConfig().getDouble("Armors_WitherChestplate.BonusHealth")),
    Armors_WitherLeggings_KBResist(getConfig().getDouble("Armors_WitherLeggings.KBResist")),
    Armors_WitherLeggings_BonusHealth(getConfig().getDouble("Armors_WitherLeggings.BonusHealth")),
    Armors_WitherBoots_KBResist(getConfig().getDouble("Armors_WitherBoots.KBResist")),
    Armors_WitherBoots_BonusHealth(getConfig().getDouble("Armors_WitherBoots.BonusHealth")),
    // BOWS
    Bows_SwordBow_Damage(getConfig().getDouble("Bows_SwordBow.Damage")),
    Bows_SwordBow_Speed(getConfig().getDouble("Bows_SwordBow.Speed")),
    Bows_HeavySwordBow_Damage(getConfig().getDouble("Bows_HeavySwordBow.Damage")),
    Bows_HeavySwordBow_Speed(getConfig().getDouble("Bows_HeavySwordBow.Speed")),
    Bows_HeavySwordBow_MoveSpeed(getConfig().getDouble("Bows_HeavySwordBow.MoveSpeed")),
    Bows_HeavySwordBow_OffhandMoveSpeed(getConfig().getDouble("Bows_HeavySwordBow.OffhandMoveSpeed")),
    Bows_HeavySwordBow_KBResist(getConfig().getDouble("Bows_HeavySwordBow.KBResist")),
    Bows_HeavySwordBow_OffhandKBResist(getConfig().getDouble("Bows_HeavySwordBow.OffhandKBResist")),
    Bows_LongSwordBow_Damage(getConfig().getDouble("Bows_LongSwordBow.Damage")),
    Bows_LongSwordBow_Speed(getConfig().getDouble("Bows_LongSwordBow.Speed")),
    Bows_LongBow_ArrowSpeed(getConfig().getDouble("Bows_LongBow.ArrowSpeed")),
    Bows_LongBow_DmgMultiplier(getConfig().getDouble("Bows_LongBow.DmgMultiplier")),
    Bows_RecurveBow_ArrowSpeed(getConfig().getDouble("Bows_RecurveBow.ArrowSpeed")),
    Bows_RecurveBow_DmgMultiplier(getConfig().getDouble("Bows_RecurveBow.DmgMultiplier")),
    Bows_CompoundBow_ArrowSpeed(getConfig().getDouble("Bows_CompoundBow.ArrowSpeed")),
    Bows_CompoundBow_DmgMultiplier(getConfig().getDouble("Bows_CompoundBow.DmgMultiplier")),
    // CHARMS
    Charms_EmeraldCharm_BonusHealth(getConfig().getDouble("Charms_EmeraldCharm.BonusHealth")),
    Charms_EmeraldCharm_BonusArmor(getConfig().getDouble("Charms_EmeraldCharm.BonusArmor")),
    Charms_BlazeCharm_BonusDamage(getConfig().getDouble("Charms_BlazeCharm.BonusDamage")),
    Charms_BlazeCharm_BonusHealth(getConfig().getDouble("Charms_BlazeCharm.BonusHealth")),
    Charms_GoldCharm_BonusAttackSpeedPercent(getConfig().getDouble("Charms_BlazeCharm.BonusAttackSpeedPercent")),
    Charms_GoldCharm_BonusMoveSpeedPercent(getConfig().getDouble("Charms_BlazeCharm.BonusMoveSpeedPercent")),
    // OTHERS
    Others_InfusedVessel_Damage(getConfig().getDouble("Others_InfusedVessel.Damage")),
    Others_InfusedVessel_Speed(getConfig().getDouble("Others_InfusedVessel.Speed")),
    Others_CursedVessel_Damage(getConfig().getDouble("Others_CursedVessel.Damage")),
    Others_CursedVessel_Speed(getConfig().getDouble("Others_CursedVessel.Speed")),
    Others_AwakenedVesselPurple_Damage(getConfig().getDouble("Others_AwakenedVesselPurple.Damage")),
    Others_AwakenedVesselPurple_Speed(getConfig().getDouble("Others_AwakenedVesselPurple.Speed")),
    Others_AwakenedVesselWhite_Damage(getConfig().getDouble("Others_AwakenedVesselWhite.Damage")),
    Others_AwakenedVesselWhite_Speed(getConfig().getDouble("Others_AwakenedVesselWhite.Speed")),
    Others_VolcanicBlade_Damage(getConfig().getDouble("Others_VolcanicBlade.Damage")),
    Others_VolcanicBlade_Speed(getConfig().getDouble("Others_VolcanicBlade.Speed")),
    Others_VolcanicSpear_Damage(getConfig().getDouble("Others_VolcanicSpear.Damage")),
    Others_VolcanicSpear_Speed(getConfig().getDouble("Others_VolcanicSpear.Speed")),
    Others_VolcanicAxe_Damage(getConfig().getDouble("Others_VolcanicAxe.Damage")),
    Others_VolcanicAxe_Speed(getConfig().getDouble("Others_VolcanicAxe.Speed")),
    Others_VolcanicCleaver_Damage(getConfig().getDouble("Others_VolcanicCleaver.Damage")),
    Others_VolcanicCleaver_Speed(getConfig().getDouble("Others_VolcanicCleaver.Speed")),
    Others_PrismarinePickaxe_Damage(getConfig().getDouble("Others_PrismarinePickaxe.Damage")),
    Others_PrismarinePickaxe_Speed(getConfig().getDouble("Others_PrismarinePickaxe.Speed")),
    Others_PrismarineAxe_Damage(getConfig().getDouble("Others_PrismarineAxe.Damage")),
    Others_PrismarineAxe_Speed(getConfig().getDouble("Others_PrismarineAxe.Speed")),
    Others_PrismarineShovel_Damage(getConfig().getDouble("Others_PrismarineShovel.Damage")),
    Others_PrismarineShovel_Speed(getConfig().getDouble("Others_PrismarineShovel.Speed")),
    Others_PrismarineHoe_Damage(getConfig().getDouble("Others_PrismarineHoe.Damage")),
    Others_PrismarineHoe_Speed(getConfig().getDouble("Others_PrismarineHoe.Speed")),
    // SWORDS
    Swords_EmeraldSword_Damage(getConfig().getDouble("Swords_EmeraldSword.Damage")),
    Swords_EmeraldSword_Speed(getConfig().getDouble("Swords_EmeraldSword.Speed")),
    Swords_ChorusBlade_Damage(getConfig().getDouble("Swords_ChorusBlade.Damage")),
    Swords_ChorusBlade_Speed(getConfig().getDouble("Swords_ChorusBlade.Speed")),
    Swords_PrismarineSword_Damage(getConfig().getDouble("Swords_PrismarineSword.Damage")),
    Swords_PrismarineSword_Speed(getConfig().getDouble("Swords_PrismarineSword.Speed"));


    private final double value;

    ConfigurationsDouble(double value){
        this.value = value;
    }
    public double getValue(){
        return this.value;
    }
}
