package me.helleo.cwp.configurations;

import org.bukkit.Bukkit;

import static me.helleo.cwp.CombatWeaponryPlus.pluginName;

public enum ConfigurationsDouble {
    // ENCHANT LEVELS
    EmeraldArmorEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Unbreaking")),
    EmeraldArmorEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Mending")),
    EmeraldGearEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Unbreaking")),
    EmeraldGearEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Mending")),
    ChorusEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("ChorusEnchantLevels.Unbreaking")),
    ChorusEnchantLevels_Knockback(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("ChorusEnchantLevels.KnockBack")),
    SwordBowEnchantLevels_Smite(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("SwordBowEnchantLevels.Smite")),
    SwordBowEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("SwordBowEnchantLevels.Unbreaking")),
    SwordBowEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("SwordBowEnchantLevels.Mending")),
    HeavySwordBowEnchantLevels_Smite(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Smite")),
    HeavySwordBowEnchantLevels_Power(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Power")),
    HeavySwordBowEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Unbreaking")),
    HeavySwordBowEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Mending")),
    PlatedChainmailEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("PlatedChainmailEnchantLevels.Unbreaking")),
    ObsidianEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("ObsidianEnchantLevels.Unbreaking")),
    DiamondShieldEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("DiamondShieldEnchantLevels.Unbreaking")),
    NetheriteShieldEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("NetheriteShieldEnchantLevels.Unbreaking")),
    // MULTIPLIERS
    MultiplierKnives(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierKnives")),
    MultiplierRapiers(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierRapiers")),
    MultiplierKatanas(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierKatanas")),
    MultiplierScythes(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierScythes")),
    MultiplierLongswords(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierLongswords")),
    MultiplierSpears(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierSpears")),
    MultiplierSabers(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierSabers")),
    MultiplierCleavers(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierCleavers")),
    // ARMORS
    Armors_RedstoneCore_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_RedstoneCore.Armor")),
    Armors_EmeraldHelmet_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldHelmet.Armor")),
    Armors_EmeraldHelmet_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldHelmet.BonusHealth")),
    Armors_EmeraldChestplate_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldChestplate.Armor")),
    Armors_EmeraldChestplate_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldChestplate.BonusHealth")),
    Armors_EmeraldLeggings_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldLeggings.Armor")),
    Armors_EmeraldLeggings_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldLeggings.BonusHealth")),
    Armors_EmeraldBoots_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldBoots.Armor")),
    Armors_EmeraldBoots_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldBoots.BonusHealth")),
    Armors_PlateChainHelmet_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainHelmet.Armor")),
    Armors_PlateChainChestplate_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainChestplate.Armor")),
    Armors_PlateChainLeggings_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainLeggings.Armor")),
    Armors_PlateChainBoots_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainBoots.Armor")),
    Armors_PrismarineHelmet_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.Armor")),
    Armors_PrismarineHelmet_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.ArmorToughness")),
    Armors_PrismarineHelmet_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.KBResist")),
    Armors_PrismarineHelmet_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.BonusHealth")),
    Armors_PrismarineChestplate_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.Armor")),
    Armors_PrismarineChestplate_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.ArmorToughness")),
    Armors_PrismarineChestplate_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.KBResist")),
    Armors_PrismarineChestplate_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.BonusHealth")),
    Armors_PrismarineLeggings_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.Armor")),
    Armors_PrismarineLeggings_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.ArmorToughness")),
    Armors_PrismarineLeggings_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.KBResist")),
    Armors_PrismarineLeggings_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.BonusHealth")),
    Armors_PrismarineBoots_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.Armor")),
    Armors_PrismarineBoots_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.ArmorToughness")),
    Armors_PrismarineBoots_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.KBResist")),
    Armors_PrismarineBoots_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.BonusHealth")),
    Armors_WitherHelmet_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherHelmet.KBResist")),
    Armors_WitherHelmet_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherHelmet.BonusHealth")),
    Armors_WitherChestplate_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherChestplate.KBResist")),
    Armors_WitherChestplate_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherChestplate.BonusHealth")),
    Armors_WitherLeggings_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherLeggings.KBResist")),
    Armors_WitherLeggings_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherLeggings.BonusHealth")),
    Armors_WitherBoots_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherBoots.KBResist")),
    Armors_WitherBoots_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherBoots.BonusHealth")),
    // BOWS
    Bows_SwordBow_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_SwordBow.Damage")),
    Bows_SwordBow_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_SwordBow.Speed")),
    Bows_HeavySwordBow_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.Damage")),
    Bows_HeavySwordBow_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.Speed")),
    Bows_HeavySwordBow_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.MoveSpeed")),
    Bows_HeavySwordBow_OffhandMoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.OffhandMoveSpeed")),
    Bows_HeavySwordBow_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.KBResist")),
    Bows_HeavySwordBow_OffhandKBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.OffhandKBResist")),
    Bows_LongSwordBow_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_LongSwordBow.Damage")),
    Bows_LongSwordBow_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_LongSwordBow.Speed")),
    Bows_LongBow_ArrowSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_LongBow.ArrowSpeed")),
    Bows_LongBow_DmgMultiplier(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_LongBow.DmgMultiplier")),
    Bows_RecurveBow_ArrowSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_RecurveBow.ArrowSpeed")),
    Bows_RecurveBow_DmgMultiplier(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_RecurveBow.DmgMultiplier")),
    Bows_CompoundBow_ArrowSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_CompoundBow.ArrowSpeed")),
    Bows_CompoundBow_DmgMultiplier(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_CompoundBow.DmgMultiplier")),
    // CHARMS
    Charms_EmeraldCharm_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_EmeraldCharm.BonusHealth")),
    Charms_EmeraldCharm_BonusArmor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_EmeraldCharm.BonusArmor")),
    Charms_BlazeCharm_BonusDamage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusDamage")),
    Charms_BlazeCharm_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusHealth")),
    Charms_GoldCharm_BonusAttackSpeedPercent(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusAttackSpeedPercent")),
    Charms_GoldCharm_BonusMoveSpeedPercent(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusMoveSpeedPercent")),
    // OTHERS
    Others_InfusedVessel_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_InfusedVessel.Damage")),
    Others_InfusedVessel_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_InfusedVessel.Speed")),
    Others_CursedVessel_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_CursedVessel.Damage")),
    Others_CursedVessel_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_CursedVessel.Speed")),
    Others_AwakenedVesselPurple_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselPurple.Damage")),
    Others_AwakenedVesselPurple_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselPurple.Speed")),
    Others_AwakenedVesselWhite_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselWhite.Damage")),
    Others_AwakenedVesselWhite_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselWhite.Speed")),
    Others_VolcanicBlade_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicBlade.Damage")),
    Others_VolcanicBlade_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicBlade.Speed")),
    Others_VolcanicSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicSpear.Damage")),
    Others_VolcanicSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicSpear.Speed")),
    Others_VolcanicAxe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicAxe.Damage")),
    Others_VolcanicAxe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicAxe.Speed")),
    Others_VolcanicCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicCleaver.Damage")),
    Others_VolcanicCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicCleaver.Speed")),
    Others_PrismarinePickaxe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarinePickaxe.Damage")),
    Others_PrismarinePickaxe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarinePickaxe.Speed")),
    Others_PrismarineAxe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineAxe.Damage")),
    Others_PrismarineAxe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineAxe.Speed")),
    Others_PrismarineShovel_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineShovel.Damage")),
    Others_PrismarineShovel_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineShovel.Speed")),
    Others_PrismarineHoe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineHoe.Damage")),
    Others_PrismarineHoe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineHoe.Speed")),
    // SWORDS
    Swords_EmeraldSword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_EmeraldSword.Damage")),
    Swords_EmeraldSword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_EmeraldSword.Speed")),
    Swords_ChorusBlade_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_ChorusBlade.Damage")),
    Swords_ChorusBlade_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_ChorusBlade.Speed")),
    Swords_PrismarineSword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_PrismarineSword.Damage")),
    Swords_PrismarineSword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_PrismarineSword.Speed"));


    private final double value;

    ConfigurationsDouble(double value){
        this.value = value;
    }
    public double getValue(){
        return this.value;
    }
}
