package me.helleo.cwp.configurations;

import org.bukkit.Bukkit;

import static me.helleo.cwp.CombatWeaponryPlus.pluginName;

public enum ConfigurationsDouble {
    // ENCHANT LEVELS
    EmeraldArmorEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Unbreaking")),
    EmeraldArmorEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Mending")),
    EmeraldGearEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Unbreaking")),
    EmeraldGearEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("EmeraldArmorEnchantLevels.Mending")),
    ChorusEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("ChorusEnchantLevels.Unbreaking")),
    ChorusEnchantLevels_Knockback(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("ChorusEnchantLevels.KnockBack")),
    SwordBowEnchantLevels_Smite(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("SwordBowEnchantLevels.Smite")),
    SwordBowEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("SwordBowEnchantLevels.Unbreaking")),
    SwordBowEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("SwordBowEnchantLevels.Mending")),
    HeavySwordBowEnchantLevels_Smite(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Smite")),
    HeavySwordBowEnchantLevels_Power(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Power")),
    HeavySwordBowEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Unbreaking")),
    HeavySwordBowEnchantLevels_Mending(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("HeavySwordBowEnchantLevels.Mending")),
    PlatedChainmailEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("PlatedChainmailEnchantLevels.Unbreaking")),
    ObsidianEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("ObsidianEnchantLevels.Unbreaking")),
    DiamondShieldEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("DiamondShieldEnchantLevels.Unbreaking")),
    NetheriteShieldEnchantLevels_Unbreaking(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("NetheriteShieldEnchantLevels.Unbreaking")),
    // MULTIPLIERS
    MultiplierKnives(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierKnives")),
    MultiplierRapiers(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierRapiers")),
    MultiplierKatanas(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierKatanas")),
    MultiplierScythes(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierScythes")),
    MultiplierLongswords(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierLongswords")),
    MultiplierSpears(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierSpears")),
    MultiplierSabers(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierSabers")),
    MultiplierCleavers(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("MultiplierCleavers")),
    // ARMORS
    Armors_RedstoneCore_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_RedstoneCore.Armor")),
    Armors_EmeraldHelmet_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldHelmet.Armor")),
    Armors_EmeraldHelmet_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldHelmet.BonusHealth")),
    Armors_EmeraldChestplate_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldChestplate.Armor")),
    Armors_EmeraldChestplate_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldChestplate.BonusHealth")),
    Armors_EmeraldLeggings_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldLeggings.Armor")),
    Armors_EmeraldLeggings_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldLeggings.BonusHealth")),
    Armors_EmeraldBoots_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldBoots.Armor")),
    Armors_EmeraldBoots_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_EmeraldBoots.BonusHealth")),
    Armors_PlateChainHelmet_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainHelmet.Armor")),
    Armors_PlateChainChestplate_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainChestplate.Armor")),
    Armors_PlateChainLeggings_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainLeggings.Armor")),
    Armors_PlateChainBoots_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PlateChainBoots.Armor")),
    Armors_PrismarineHelmet_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.Armor")),
    Armors_PrismarineHelmet_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.ArmorToughness")),
    Armors_PrismarineHelmet_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.KBResist")),
    Armors_PrismarineHelmet_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineHelmet.BonusHealth")),
    Armors_PrismarineChestplate_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.Armor")),
    Armors_PrismarineChestplate_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.ArmorToughness")),
    Armors_PrismarineChestplate_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.KBResist")),
    Armors_PrismarineChestplate_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineChestplate.BonusHealth")),
    Armors_PrismarineLeggings_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.Armor")),
    Armors_PrismarineLeggings_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.ArmorToughness")),
    Armors_PrismarineLeggings_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.KBResist")),
    Armors_PrismarineLeggings_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineLeggings.BonusHealth")),
    Armors_PrismarineBoots_Armor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.Armor")),
    Armors_PrismarineBoots_ArmorToughness(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.ArmorToughness")),
    Armors_PrismarineBoots_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.KBResist")),
    Armors_PrismarineBoots_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_PrismarineBoots.BonusHealth")),
    Armors_WitherHelmet_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherHelmet.KBResist")),
    Armors_WitherHelmet_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherHelmet.BonusHealth")),
    Armors_WitherChestplate_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherChestplate.KBResist")),
    Armors_WitherChestplate_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherChestplate.BonusHealth")),
    Armors_WitherLeggings_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherLeggings.KBResist")),
    Armors_WitherLeggings_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherLeggings.BonusHealth")),
    Armors_WitherBoots_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherBoots.KBResist")),
    Armors_WitherBoots_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Armors_WitherBoots.BonusHealth")),
    // BOWS
    Bows_SwordBow_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_SwordBow.Damage")),
    Bows_SwordBow_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_SwordBow.Speed")),
    Bows_HeavySwordBow_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.Damage")),
    Bows_HeavySwordBow_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.Speed")),
    Bows_HeavySwordBow_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.MoveSpeed")),
    Bows_HeavySwordBow_OffhandMoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.OffhandMoveSpeed")),
    Bows_HeavySwordBow_KBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.KBResist")),
    Bows_HeavySwordBow_OffhandKBResist(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_HeavySwordBow.OffhandKBResist")),
    Bows_LongBow_ArrowSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_LongBow.ArrowSpeed")),
    Bows_LongBow_DmgMultiplier(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_LongBow.DmgMultiplier")),
    Bows_RecurveBow_ArrowSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_RecurveBow.ArrowSpeed")),
    Bows_RecurveBow_DmgMultiplier(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_RecurveBow.DmgMultiplier")),
    Bows_CompoundBow_ArrowSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_CompoundBow.ArrowSpeed")),
    Bows_CompoundBow_DmgMultiplier(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Bows_CompoundBow.DmgMultiplier")),
    // CHARMS
    Charms_EmeraldCharm_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_EmeraldCharm.BonusHealth")),
    Charms_EmeraldCharm_BonusArmor(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_EmeraldCharm.BonusArmor")),
    Charms_BlazeCharm_BonusDamage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusDamage")),
    Charms_BlazeCharm_BonusHealth(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusHealth")),
    Charms_GoldCharm_BonusAttackSpeedPercent(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusAttackSpeedPercent")),
    Charms_GoldCharm_BonusMoveSpeedPercent(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Charms_BlazeCharm.BonusMoveSpeedPercent")),
    // OTHERS
    Others_InfusedVessel_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_InfusedVessel.Damage")),
    Others_InfusedVessel_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_InfusedVessel.Speed")),
    Others_CursedVessel_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_CursedVessel.Damage")),
    Others_CursedVessel_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_CursedVessel.Speed")),
    Others_AwakenedVesselPurple_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselPurple.Damage")),
    Others_AwakenedVesselPurple_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselPurple.Speed")),
    Others_AwakenedVesselWhite_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselWhite.Damage")),
    Others_AwakenedVesselWhite_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_AwakenedVesselWhite.Speed")),
    Others_VolcanicBlade_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicBlade.Damage")),
    Others_VolcanicBlade_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicBlade.Speed")),
    Others_VolcanicSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicSpear.Damage")),
    Others_VolcanicSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicSpear.Speed")),
    Others_VolcanicAxe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicAxe.Damage")),
    Others_VolcanicAxe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicAxe.Speed")),
    Others_VolcanicCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicCleaver.Damage")),
    Others_VolcanicCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_VolcanicCleaver.Speed")),
    Others_PrismarinePickaxe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarinePickaxe.Damage")),
    Others_PrismarinePickaxe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarinePickaxe.Speed")),
    Others_PrismarineAxe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineAxe.Damage")),
    Others_PrismarineAxe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineAxe.Speed")),
    Others_PrismarineShovel_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineShovel.Damage")),
    Others_PrismarineShovel_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineShovel.Speed")),
    Others_PrismarineHoe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineHoe.Damage")),
    Others_PrismarineHoe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Others_PrismarineHoe.Speed")),
    // SWORDS
    Swords_EmeraldSword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_EmeraldSword.Damage")),
    Swords_EmeraldSword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_EmeraldSword.Speed")),
    Swords_ChorusBlade_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_ChorusBlade.Damage")),
    Swords_ChorusBlade_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_ChorusBlade.Speed")),
    Swords_PrismarineSword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_PrismarineSword.Damage")),
    Swords_PrismarineSword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Swords_PrismarineSword.Speed")),
    // SCYTHES
    Scythes_WoodenScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_WoodenScythe.Damage")),
    Scythes_WoodenScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_WoodenScythe.Speed")),
    Scythes_GoldenScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_GoldenScythe.Damage")),
    Scythes_GoldenScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_GoldenScythe.Speed")),
    Scythes_StoneScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_StoneScythe.Damage")),
    Scythes_StoneScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_StoneScythe.Speed")),
    Scythes_IronScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_IronScythe.Damage")),
    Scythes_IronScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_IronScythe.Speed")),
    Scythes_EmeraldScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_EmeraldScythe.Damage")),
    Scythes_EmeraldScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_EmeraldScythe.Speed")),
    Scythes_DiamondScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_WoodenScythe.Damage")),
    Scythes_DiamondScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_WoodenScythe.Speed")),
    Scythes_NetheriteScythe_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_NetheriteScythe.Damage")),
    Scythes_NetheriteScythe_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_NetheriteScythe.Speed")),
    Scythes_PrismarineScythe_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Scythes_PrismarineScythe.DamageAdded")),
    // RAPIERS
    Rapiers_WoodenRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_WoodenRapier.Damage")),
    Rapiers_WoodenRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_WoodenRapier.Speed")),
    Rapiers_GoldenRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_GoldenRapier.Damage")),
    Rapiers_GoldenRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_GoldenRapier.Speed")),
    Rapiers_StoneRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_StoneRapier.Damage")),
    Rapiers_StoneRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_StoneRapier.Speed")),
    Rapiers_IronRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_IronRapier.Damage")),
    Rapiers_IronRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_IronRapier.Speed")),
    Rapiers_EmeraldRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_EmeraldRapier.Damage")),
    Rapiers_EmeraldRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_EmeraldRapier.Speed")),
    Rapiers_DiamondRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_DiamondRapier.Damage")),
    Rapiers_DiamondRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_DiamondRapier.Speed")),
    Rapiers_NetheriteRapier_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_NetheriteRapier.Damage")),
    Rapiers_NetheriteRapier_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_NetheriteRapier.Speed")),
    Rapiers_PrismarineRapier_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Rapiers_PrismarineRapier.DamageAdded")),
    // LONGSWORDS
    Longswords_WoodenLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_WoodenLongsword.Damage")),
    Longswords_WoodenLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_WoodenLongsword.Speed")),
    Longswords_GoldenLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_GoldenLongsword.Damage")),
    Longswords_GoldenLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_GoldenLongsword.Speed")),
    Longswords_StoneLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_StoneLongsword.Damage")),
    Longswords_StoneLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_StoneLongsword.Speed")),
    Longswords_IronLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_IronLongsword.Damage")),
    Longswords_IronLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_IronLongsword.Speed")),
    Longswords_EmeraldLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_EmeraldLongsword.Damage")),
    Longswords_EmeraldLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_EmeraldLongsword.Speed")),
    Longswords_DiamondLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_DiamondLongsword.Damage")),
    Longswords_DiamondLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_DiamondLongsword.Speed")),
    Longswords_NetheriteLongsword_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_NetheriteLongsword.Damage")),
    Longswords_NetheriteLongsword_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_NetheriteLongsword.Speed")),
    Longswords_PrismarineLongsword_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Longswords_PrismarineLongsword.DamageAdded")),
    // KNIVES
    Knives_WoodenKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_WoodenKnife.Damage")),
    Knives_WoodenKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_WoodenKnife.Speed")),
    Knives_GoldenKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_GoldenKnife.Damage")),
    Knives_GoldenKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_GoldenKnife.Speed")),
    Knives_StoneKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_StoneKnife.Damage")),
    Knives_StoneKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_StoneKnife.Speed")),
    Knives_IronKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_IronKnife.Damage")),
    Knives_IronKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_IronKnife.Speed")),
    Knives_EmeraldKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_EmeraldKnife.Damage")),
    Knives_EmeraldKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_EmeraldKnife.Speed")),
    Knives_DiamondKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_DiamondKnife.Damage")),
    Knives_DiamondKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_DiamondKnife.Speed")),
    Knives_NetheriteKnife_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_NetheriteKnife.Damage")),
    Knives_NetheriteKnife_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_NetheriteKnife.Speed")),
    Knives_PrismarineKnife_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Knives_PrismarineKnife.DamageAdded")),
    // SPEARS
    Spears_WoodenSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_WoodenSpear.Damage")),
    Spears_WoodenSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_WoodenSpear.Speed")),
    Spears_GoldenSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_GoldenSpear.Damage")),
    Spears_GoldenSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_GoldenSpear.Speed")),
    Spears_StoneSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_StoneSpear.Damage")),
    Spears_StoneSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_StoneSpear.Speed")),
    Spears_IronSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_IronSpear.Damage")),
    Spears_IronSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_IronSpear.Speed")),
    Spears_EmeraldSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_EmeraldSpear.Damage")),
    Spears_EmeraldSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_EmeraldSpear.Speed")),
    Spears_DiamondSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_DiamondSpear.Damage")),
    Spears_DiamondSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_DiamondSpear.Speed")),
    Spears_NetheriteSpear_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_NetheriteSpear.Damage")),
    Spears_NetheriteSpear_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_NetheriteSpear.Speed")),
    Spears_PrismarineSpear_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Spears_PrismarineSpear.DamageAdded")),
    // KATANAS
    Katanas_WoodenKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_WoodenKatana.Damage")),
    Katanas_WoodenKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_WoodenKatana.Speed")),
    Katanas_WoodenKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_WoodenKatana.MoveSpeed")),
    Katanas_GoldenKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_GoldenKatana.Damage")),
    Katanas_GoldenKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_GoldenKatana.Speed")),
    Katanas_GoldenKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_GoldenKatana.MoveSpeed")),
    Katanas_StoneKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_StoneKatana.Damage")),
    Katanas_StoneKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_StoneKatana.Speed")),
    Katanas_StoneKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_StoneKatana.MoveSpeed")),
    Katanas_IronKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_IronKatana.Damage")),
    Katanas_IronKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_IronKatana.Speed")),
    Katanas_IronKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_IronKatana.MoveSpeed")),
    Katanas_EmeraldKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_EmeraldKatana.Damage")),
    Katanas_EmeraldKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_EmeraldKatana.Speed")),
    Katanas_EmeraldKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_EmeraldKatana.MoveSpeed")),
    Katanas_DiamondKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_DiamondKatana.Damage")),
    Katanas_DiamondKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_DiamondKatana.Speed")),
    Katanas_DiamondKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_DiamondKatana.MoveSpeed")),
    Katanas_NetheriteKatana_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_NetheriteKatana.Damage")),
    Katanas_NetheriteKatana_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_NetheriteKatana.Speed")),
    Katanas_NetheriteKatana_MoveSpeed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_NetheriteKatana.MoveSpeed")),
    Katanas_PrismarineKatana_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Katanas_PrismarineKatana.DamageAdded")),
    // SABERS
    Sabers_WoodenSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_WoodenSaber.Damage")),
    Sabers_WoodenSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_WoodenSaber.Speed")),
    Sabers_GoldenSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_GoldenSaber.Damage")),
    Sabers_GoldenSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_GoldenSaber.Speed")),
    Sabers_StoneSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_StoneSaber.Damage")),
    Sabers_StoneSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_StoneSaber.Speed")),
    Sabers_IronSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_IronSaber.Damage")),
    Sabers_IronSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_IronSaber.Speed")),
    Sabers_EmeraldSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_EmeraldSaber.Damage")),
    Sabers_EmeraldSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_EmeraldSaber.Speed")),
    Sabers_DiamondSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_DiamondSaber.Damage")),
    Sabers_DiamondSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_DiamondSaber.Speed")),
    Sabers_NetheriteSaber_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_NetheriteSaber.Damage")),
    Sabers_NetheriteSaber_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_NetheriteSaber.Speed")),
    Sabers_PrismarineSaber_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Sabers_PrismarineSaber.DamageAdded")),
    // CLEAVERS
    Cleavers_WoodenCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_WoodenCleaver.Damage")),
    Cleavers_WoodenCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_WoodenCleaver.Speed")),
    Cleavers_GoldenCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_GoldenCleaver.Damage")),
    Cleavers_GoldenCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_GoldenCleaver.Speed")),
    Cleavers_StoneCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_StoneCleaver.Damage")),
    Cleavers_StoneCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_StoneCleaver.Speed")),
    Cleavers_IronCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_IronCleaver.Damage")),
    Cleavers_IronCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_IronCleaver.Speed")),
    Cleavers_EmeraldCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_EmeraldCleaver.Damage")),
    Cleavers_EmeraldCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_EmeraldCleaver.Speed")),
    Cleavers_DiamondCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_DiamondCleaver.Damage")),
    Cleavers_DiamondCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_DiamondCleaver.Speed")),
    Cleavers_NetheriteCleaver_Damage(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_NetheriteCleaver.Damage")),
    Cleavers_NetheriteCleaver_Speed(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_NetheriteCleaver.Speed")),
    Cleavers_PrismarineCleaver_DamageAdded(Bukkit.getPluginManager().getPlugin(pluginName).getConfig().getDouble("Cleavers_PrismarineCleaver.DamageAdded")),
    //adicionar o resto das armaduras
    ;


    private final double value;

    ConfigurationsDouble(double value){
        this.value = value;
    }
    public double getValue(){
        return this.value;
    }
}
